//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/InputSystem_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputSystem_Actions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputSystem_Actions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""056e52f3-96d3-4822-b709-33edf80a5d72"",
            ""actions"": [
                {
                    ""name"": ""SpawnLeftMelee"",
                    ""type"": ""Button"",
                    ""id"": ""deead41a-dcc4-4148-946e-b5450cc033f0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnLeftRanged"",
                    ""type"": ""Button"",
                    ""id"": ""3da3bb80-202a-426c-8fc6-abe88b028f32"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnLeftHeavy"",
                    ""type"": ""Button"",
                    ""id"": ""2051552a-4eda-46df-960d-a84d18c4f117"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnRightMelee"",
                    ""type"": ""Button"",
                    ""id"": ""65070617-4800-44d1-ad51-2dd0b9c4b66b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnRightRanged"",
                    ""type"": ""Button"",
                    ""id"": ""35469968-044f-4a00-82a0-e9a848aee7c7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnRightHeavy"",
                    ""type"": ""Button"",
                    ""id"": ""6483c117-4662-41e9-86ee-9901d2155422"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseLeftTop"",
                    ""type"": ""Button"",
                    ""id"": ""22e1f6f1-dda4-41a7-98ed-67ccf6d89e65"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseLeftBottom"",
                    ""type"": ""Button"",
                    ""id"": ""4b4afc11-59be-41ef-b034-f55fd9845c2f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseRightTop"",
                    ""type"": ""Button"",
                    ""id"": ""79a7a8b7-86d1-4d23-a22d-64fd4fd5fe96"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseRightBottom"",
                    ""type"": ""Button"",
                    ""id"": ""866415c3-a112-4836-8eab-472eb9a84bf7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aa565fc4-5b21-4bd9-aec7-b00e5c7f2ba1"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnLeftMelee"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fc860b4-e54b-44b9-a253-3817693452b2"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnLeftRanged"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ae5c292-f5f2-4a3e-95d9-dcf5a6aba950"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnLeftHeavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e5a12c4-fb71-4dc9-9ab3-b20b1c6767a0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnRightMelee"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2ac1ee0-b292-4a24-8c80-3e867ecd52fc"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnRightRanged"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b97fca9d-63ac-44ef-bc28-99c1966f19c0"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnRightHeavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b690a361-37ca-4d81-87c9-a9d5a7d01cc0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseLeftTop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3ef03df-d9f2-4326-a0d7-b17cfdda3e8b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseLeftBottom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""598bed03-37c8-476c-a332-e36f0d9eee48"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseRightTop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4923f79-a98d-4a38-9ff2-bb9830af8d9a"",
                    ""path"": ""<Keyboard>/rightCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseRightBottom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_SpawnLeftMelee = m_Gameplay.FindAction("SpawnLeftMelee", throwIfNotFound: true);
        m_Gameplay_SpawnLeftRanged = m_Gameplay.FindAction("SpawnLeftRanged", throwIfNotFound: true);
        m_Gameplay_SpawnLeftHeavy = m_Gameplay.FindAction("SpawnLeftHeavy", throwIfNotFound: true);
        m_Gameplay_SpawnRightMelee = m_Gameplay.FindAction("SpawnRightMelee", throwIfNotFound: true);
        m_Gameplay_SpawnRightRanged = m_Gameplay.FindAction("SpawnRightRanged", throwIfNotFound: true);
        m_Gameplay_SpawnRightHeavy = m_Gameplay.FindAction("SpawnRightHeavy", throwIfNotFound: true);
        m_Gameplay_ChooseLeftTop = m_Gameplay.FindAction("ChooseLeftTop", throwIfNotFound: true);
        m_Gameplay_ChooseLeftBottom = m_Gameplay.FindAction("ChooseLeftBottom", throwIfNotFound: true);
        m_Gameplay_ChooseRightTop = m_Gameplay.FindAction("ChooseRightTop", throwIfNotFound: true);
        m_Gameplay_ChooseRightBottom = m_Gameplay.FindAction("ChooseRightBottom", throwIfNotFound: true);
    }

    ~@GameInputActions()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, GameInputActions.Gameplay.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_SpawnLeftMelee;
    private readonly InputAction m_Gameplay_SpawnLeftRanged;
    private readonly InputAction m_Gameplay_SpawnLeftHeavy;
    private readonly InputAction m_Gameplay_SpawnRightMelee;
    private readonly InputAction m_Gameplay_SpawnRightRanged;
    private readonly InputAction m_Gameplay_SpawnRightHeavy;
    private readonly InputAction m_Gameplay_ChooseLeftTop;
    private readonly InputAction m_Gameplay_ChooseLeftBottom;
    private readonly InputAction m_Gameplay_ChooseRightTop;
    private readonly InputAction m_Gameplay_ChooseRightBottom;
    /// <summary>
    /// Provides access to input actions defined in input action map "Gameplay".
    /// </summary>
    public struct GameplayActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GameplayActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/SpawnLeftMelee".
        /// </summary>
        public InputAction @SpawnLeftMelee => m_Wrapper.m_Gameplay_SpawnLeftMelee;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/SpawnLeftRanged".
        /// </summary>
        public InputAction @SpawnLeftRanged => m_Wrapper.m_Gameplay_SpawnLeftRanged;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/SpawnLeftHeavy".
        /// </summary>
        public InputAction @SpawnLeftHeavy => m_Wrapper.m_Gameplay_SpawnLeftHeavy;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/SpawnRightMelee".
        /// </summary>
        public InputAction @SpawnRightMelee => m_Wrapper.m_Gameplay_SpawnRightMelee;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/SpawnRightRanged".
        /// </summary>
        public InputAction @SpawnRightRanged => m_Wrapper.m_Gameplay_SpawnRightRanged;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/SpawnRightHeavy".
        /// </summary>
        public InputAction @SpawnRightHeavy => m_Wrapper.m_Gameplay_SpawnRightHeavy;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/ChooseLeftTop".
        /// </summary>
        public InputAction @ChooseLeftTop => m_Wrapper.m_Gameplay_ChooseLeftTop;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/ChooseLeftBottom".
        /// </summary>
        public InputAction @ChooseLeftBottom => m_Wrapper.m_Gameplay_ChooseLeftBottom;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/ChooseRightTop".
        /// </summary>
        public InputAction @ChooseRightTop => m_Wrapper.m_Gameplay_ChooseRightTop;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/ChooseRightBottom".
        /// </summary>
        public InputAction @ChooseRightBottom => m_Wrapper.m_Gameplay_ChooseRightBottom;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GameplayActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @SpawnLeftMelee.started += instance.OnSpawnLeftMelee;
            @SpawnLeftMelee.performed += instance.OnSpawnLeftMelee;
            @SpawnLeftMelee.canceled += instance.OnSpawnLeftMelee;
            @SpawnLeftRanged.started += instance.OnSpawnLeftRanged;
            @SpawnLeftRanged.performed += instance.OnSpawnLeftRanged;
            @SpawnLeftRanged.canceled += instance.OnSpawnLeftRanged;
            @SpawnLeftHeavy.started += instance.OnSpawnLeftHeavy;
            @SpawnLeftHeavy.performed += instance.OnSpawnLeftHeavy;
            @SpawnLeftHeavy.canceled += instance.OnSpawnLeftHeavy;
            @SpawnRightMelee.started += instance.OnSpawnRightMelee;
            @SpawnRightMelee.performed += instance.OnSpawnRightMelee;
            @SpawnRightMelee.canceled += instance.OnSpawnRightMelee;
            @SpawnRightRanged.started += instance.OnSpawnRightRanged;
            @SpawnRightRanged.performed += instance.OnSpawnRightRanged;
            @SpawnRightRanged.canceled += instance.OnSpawnRightRanged;
            @SpawnRightHeavy.started += instance.OnSpawnRightHeavy;
            @SpawnRightHeavy.performed += instance.OnSpawnRightHeavy;
            @SpawnRightHeavy.canceled += instance.OnSpawnRightHeavy;
            @ChooseLeftTop.started += instance.OnChooseLeftTop;
            @ChooseLeftTop.performed += instance.OnChooseLeftTop;
            @ChooseLeftTop.canceled += instance.OnChooseLeftTop;
            @ChooseLeftBottom.started += instance.OnChooseLeftBottom;
            @ChooseLeftBottom.performed += instance.OnChooseLeftBottom;
            @ChooseLeftBottom.canceled += instance.OnChooseLeftBottom;
            @ChooseRightTop.started += instance.OnChooseRightTop;
            @ChooseRightTop.performed += instance.OnChooseRightTop;
            @ChooseRightTop.canceled += instance.OnChooseRightTop;
            @ChooseRightBottom.started += instance.OnChooseRightBottom;
            @ChooseRightBottom.performed += instance.OnChooseRightBottom;
            @ChooseRightBottom.canceled += instance.OnChooseRightBottom;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @SpawnLeftMelee.started -= instance.OnSpawnLeftMelee;
            @SpawnLeftMelee.performed -= instance.OnSpawnLeftMelee;
            @SpawnLeftMelee.canceled -= instance.OnSpawnLeftMelee;
            @SpawnLeftRanged.started -= instance.OnSpawnLeftRanged;
            @SpawnLeftRanged.performed -= instance.OnSpawnLeftRanged;
            @SpawnLeftRanged.canceled -= instance.OnSpawnLeftRanged;
            @SpawnLeftHeavy.started -= instance.OnSpawnLeftHeavy;
            @SpawnLeftHeavy.performed -= instance.OnSpawnLeftHeavy;
            @SpawnLeftHeavy.canceled -= instance.OnSpawnLeftHeavy;
            @SpawnRightMelee.started -= instance.OnSpawnRightMelee;
            @SpawnRightMelee.performed -= instance.OnSpawnRightMelee;
            @SpawnRightMelee.canceled -= instance.OnSpawnRightMelee;
            @SpawnRightRanged.started -= instance.OnSpawnRightRanged;
            @SpawnRightRanged.performed -= instance.OnSpawnRightRanged;
            @SpawnRightRanged.canceled -= instance.OnSpawnRightRanged;
            @SpawnRightHeavy.started -= instance.OnSpawnRightHeavy;
            @SpawnRightHeavy.performed -= instance.OnSpawnRightHeavy;
            @SpawnRightHeavy.canceled -= instance.OnSpawnRightHeavy;
            @ChooseLeftTop.started -= instance.OnChooseLeftTop;
            @ChooseLeftTop.performed -= instance.OnChooseLeftTop;
            @ChooseLeftTop.canceled -= instance.OnChooseLeftTop;
            @ChooseLeftBottom.started -= instance.OnChooseLeftBottom;
            @ChooseLeftBottom.performed -= instance.OnChooseLeftBottom;
            @ChooseLeftBottom.canceled -= instance.OnChooseLeftBottom;
            @ChooseRightTop.started -= instance.OnChooseRightTop;
            @ChooseRightTop.performed -= instance.OnChooseRightTop;
            @ChooseRightTop.canceled -= instance.OnChooseRightTop;
            @ChooseRightBottom.started -= instance.OnChooseRightBottom;
            @ChooseRightBottom.performed -= instance.OnChooseRightBottom;
            @ChooseRightBottom.canceled -= instance.OnChooseRightBottom;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />.
        /// </summary>
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GameplayActions" /> instance referencing this action map.
    /// </summary>
    public GameplayActions @Gameplay => new GameplayActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Gameplay" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
    /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
    public interface IGameplayActions
    {
        /// <summary>
        /// Method invoked when associated input action "SpawnLeftMelee" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpawnLeftMelee(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpawnLeftRanged" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpawnLeftRanged(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpawnLeftHeavy" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpawnLeftHeavy(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpawnRightMelee" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpawnRightMelee(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpawnRightRanged" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpawnRightRanged(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpawnRightHeavy" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpawnRightHeavy(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ChooseLeftTop" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChooseLeftTop(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ChooseLeftBottom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChooseLeftBottom(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ChooseRightTop" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChooseRightTop(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ChooseRightBottom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChooseRightBottom(InputAction.CallbackContext context);
    }
}
